/* Suggestion lists for autocomplete fields.
   Placeholders for the real sources (IPEDS, CIP, NCES). Every field accepts free text,
   so a missing entry never blocks a user. Swap these for API-backed lookups later. */
window.TW = window.TW || {};
TW.data = {
  majors: ['Accounting','Aerospace Engineering','Agriculture','Anthropology','Architecture','Art','Automotive Technology','Biochemistry','Biology','Biomedical Engineering','Business Administration','Chemical Engineering','Chemistry','Civil Engineering','Communications','Computer Engineering','Computer Science','Cosmetology','Criminal Justice','Culinary Arts','Cybersecurity','Data Science','Dental Hygiene','Early Childhood Education','Economics','Education','Electrical Engineering','Electrician Training','Elementary Education','English','Environmental Science','Finance','Forestry','Graphic Design','Health Sciences','History','HVAC Technology','Information Technology','International Relations','Journalism','Kinesiology','Marketing','Mathematics','Mechanical Engineering','Music','Nursing','Nutrition','Paralegal Studies','Pharmacy','Philosophy','Physical Therapy','Physics','Political Science','Pre-Law','Pre-Med','Psychology','Public Health','Radiology Technology','Social Work','Sociology','Software Engineering','Special Education','Statistics','Theater','Veterinary Science','Welding Technology'],
  institutions: ['Arizona State University','Boston University','California State University, Fullerton','Columbia University','Florida State University','Georgia Institute of Technology','Harvard University','Houston Community College','Massachusetts Institute of Technology','Miami Dade College','New York University','Northern Virginia Community College','Ohio State University','Palomar College','Pennsylvania State University','Purdue University','Rutgers University','San Diego State University','Santa Monica College','Stanford University','Texas A&M University','University of California, Berkeley','University of California, Los Angeles','University of California, San Diego','University of Florida','University of Georgia','University of Illinois Urbana-Champaign','University of Michigan','University of North Carolina at Chapel Hill','University of Texas at Austin','University of Washington','Virginia Tech'],
  cities: ['Atlanta, GA','Austin, TX','Baltimore, MD','Boston, MA','Charlotte, NC','Chicago, IL','Cleveland, OH','Columbus, OH','Dallas, TX','Denver, CO','Detroit, MI','Fallbrook, CA','Fresno, CA','Houston, TX','Indianapolis, IN','Jacksonville, FL','Kansas City, MO','Las Vegas, NV','Los Angeles, CA','Memphis, TN','Miami, FL','Milwaukee, WI','Minneapolis, MN','Nashville, TN','New Orleans, LA','New York, NY','Oklahoma City, OK','Orlando, FL','Philadelphia, PA','Phoenix, AZ','Pittsburgh, PA','Portland, OR','Raleigh, NC','Sacramento, CA','Salt Lake City, UT','San Antonio, TX','San Diego, CA','San Francisco, CA','Seattle, WA','St. Louis, MO','Tampa, FL','Tucson, AZ','Washington, DC'],
  careers: ['Aviation','Agriculture','Architecture','Accounting','Cybersecurity','Data science','Education and teaching','Entrepreneurship','Environmental science','Film and media','Finance','Firefighting','Graphic design','Journalism','Law','Law enforcement','Medicine','Mental health counseling','Network security engineering','Nursing','Pharmacy','Physical therapy','Public health','Public policy','Research science','Skilled trades','Social work','Software engineering','Veterinary medicine'],
  employers: ['Amazon','AT&T','Bank of America','Boeing','Chick-fil-A','Coca-Cola','Costco','Duke Energy','FedEx','Federal government','Ford','General Motors','HCA Healthcare','Home Depot','John Deere','Kaiser Permanente','Kroger','Lockheed Martin','Lowe\'s','McDonald\'s','Publix','School district','Starbucks','State or local government','Target','Tyson Foods','UPS','US Postal Service','Verizon','Walmart','Wells Fargo'],
  unions: ['AFSCME','AFT','CWA','IAFF (Firefighters)','IATSE','IBEW','Ironworkers','LIUNA (Laborers)','NEA','NNU','Operating Engineers','SAG-AFTRA','SEIU','Teamsters','UA (Plumbers and Pipefitters)','UAW','UFCW','USW','Carpenters'],
  fraternal: ['American Legion','Eastern Star','Elks','Grange','Job\'s Daughters','Kiwanis','Knights of Columbus','Lions Club','Masons','Moose','Odd Fellows','Optimist Club','Rotary','Ruritan','Shriners','Sons of Italy','VFW'],
  traditions: ['Baha\'i','Buddhist','Catholic','Eastern Orthodox','Hindu','Jewish','Latter-day Saints','Muslim','Protestant','Quaker','Sikh','Unitarian Universalist'],
  memberOrgs: ['Farm Bureau','Farm Credit','Golden 1 Credit Union','Navy Federal Credit Union','Nationwide','PenFed Credit Union','State Employees\' Credit Union','State Farm','Touchstone Energy Cooperative','USAA'],
  heritage: ['African American','Armenian','Basque','Chinese','Croatian','Cuban','Czech','Dutch','Filipino','Finnish','French','French Canadian','German','Greek','Hispanic or Latino','Hungarian','Indian','Irish','Italian','Japanese','Jewish','Korean','Lebanese','Lithuanian','Mexican','Native Hawaiian','Nigerian','Norwegian','Polish','Portuguese','Puerto Rican','Scottish','Swedish','Ukrainian','Vietnamese','Welsh'],
  tribes: ['Alaska Native','Apache','Blackfeet','Cherokee Nation','Cheyenne','Chickasaw Nation','Choctaw Nation','Comanche','Crow','Hopi','Iroquois (Haudenosaunee)','Lakota (Sioux)','Muscogee (Creek) Nation','Navajo Nation','Ojibwe','Pueblo','Seminole Nation'],
  languages: ['American Sign Language','Arabic','Cantonese','French','German','Haitian Creole','Hindi','Italian','Japanese','Korean','Mandarin','Navajo','Persian (Farsi)','Polish','Portuguese','Russian','Spanish','Tagalog','Urdu','Vietnamese'],
  langCodes: {'American Sign Language':'ase','Arabic':'ar','Cantonese':'yue','French':'fr','German':'de','Haitian Creole':'ht','Hindi':'hi','Italian':'it','Japanese':'ja','Korean':'ko','Mandarin':'zh','Navajo':'nv','Persian (Farsi)':'fa','Polish':'pl','Portuguese':'pt','Russian':'ru','Spanish':'es','Tagalog':'tl','Urdu':'ur','Vietnamese':'vi'},
  industries: ['Agriculture','Construction','Education','Finance','Food service','Healthcare','Hospitality','Manufacturing','Nonprofit','Retail','Technology','Transportation'],
  scholarships: ['Amazon Future Engineer','Burger King Scholars','Cameron Impact Scholarship','Coca-Cola Scholars','Dell Scholars','Elks Most Valuable Student','Fulbright','Gates Scholarship','Goldwater','Hispanic Scholarship Fund','Horatio Alger','Jack Kent Cooke','National Merit','Posse Foundation','QuestBridge','Regeneron STS','Ron Brown Scholar','Truman','UNCF']
};
